### ISSUE TITLE
Compatibility patch for HLTB and Clean Gameview

### ISSUE THREAD

**Issue by lyndonguitar** [suchmememanyskill/CssLoader-ThemeDb#125]
Currently when you add HLTB (How long to beat) Decky Plugin, it slightly shifts the Clean Gameview sizing, and lowers down the "Play button" a bit,  showing a bit of bug. 

HLTB is a very useful tool, along with Clean Gameview making things neater. It would be nice to have compatibility for both.

**Comment by EMERALD0874** [comment]
This is not a CSS Loader theme database issue. Please redirect your issue to the proper GitHub repository: https://github.com/suchmememanyskill/Steam-Deck-Themes
