### ISSUE TITLE
Change github link to decky discord

### ISSUE THREAD

**Issue by suchmememanyskill** [suchmememanyskill/CssLoader-ThemeDb#46]

**Comment by suchmememanyskill** [comment]
Resolved in [e8889b0](https://github.com/suchmememanyskill/CssLoader-ThemeDb/commit/e8889b00a806d5f40566d6758d6f82fcdac2d277)

**Comment by EMERALD0874** [comment]
Not completed yet as the fix has not been merged to the main branch.
