### ISSUE TITLE
Steps for using the CEF remote debugger do not work

### ISSUE THREAD

**Issue by ToyVo** [suchmememanyskill/CssLoader-ThemeDb#67]
As part of the installation process of the Decky Loader is of course to enable developer mode and enabling the CEF Remote Debugging. Once everything has started however, port 8081 doesn't appear to be open.

I realize that this likely isn't something that can be changed in this repository to address this, but I don't really know where else I could ask this and this repository doesn't have discussions enabled so that I could ask there instead.

**Comment by EMERALD0874** [comment]
This is tied to Decky adding a necessary CEF debugging option. You will need to go to the Decky settings and enable the CEF debugger. The README is still correct outside of this.
